[package]
name = "cache_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.8.0"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
